name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🔊 Upload code coverage to GitHub Artifacts (for SonarCloud)
        uses: actions/upload-artifact@v2
        with:
          name: cov-file
          path: app/build/reports/jacoco/jacocoTestReport/html/index.html

      - name: 🔊 Save PR number (for SonarCloud)
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.number }} > PR_NUMBER.txt

      - name: 🔊 Upload PR number to GitHub Artifacts (for SonarCloud)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: PR_NUMBER
          path: PR_NUMBER.txt